### ISSUE TITLE
When the android support will be available? 

### ISSUE THREAD

**Issue by mayureshjadhav** [arpit2438735/nativescript-tglib#1]
Hey, I am interested in the android support library. When it will be available?

**Comment by arpit2438735** [comment]
I thought no one is using it 😕 , so I hold the development of this plugin.I will start development of it and will update you with the latest.

**Comment by mayureshjadhav** [comment]
Thanks

**Comment by mayureshjadhav** [comment]
Any

**Comment by mayureshjadhav** [comment]
Any updates?

**Comment by arpit2438735** [comment]
I am not getting time to invest on this one.If you can help me out if possible that will be great.

**Comment by mayureshjadhav** [comment]
I would like to help and i feel that will improve my skills as well. How can we communicate?

**Comment by arpit2438735** [comment]
You can communicate me over arpit2438735@gmail.com
